// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. The Supabase pooler
    // (used by the runtime via DATABASE_URL) doesn't support the protocol
    // Prisma uses for migrations. Falls back to DATABASE_URL for envs that
    // only have one URL (e.g. local Postgres dev).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
